Repository luca-fiorito-11/sandy, pull requests merged in 2024-08, with the labels that each got.

#331 update installation scripts
  .github/workflows/test_notebooks.yml
  .github/workflows/unit_test.yml
  notebooks/notebook_sampling_decay_data.ipynb
  requirements.txt
  requirements_conda.txt
  sandy/__init__.py
  sandy/core/cov.py
  sandy/core/endf6.py
  sandy/core/records.py
  sandy/fy.py
  sandy/sections/mf32.py
  setup.cfg
  setup.py
Labels: bug

#332 Parsing MF35 in ERRORR output
  sandy/constants.py
  sandy/errorr.py
  sandy/librwfortra.HNMZAH7GGM6VMU3TLJ5LCYWAHUEDVVXS.gfortran-win_amd64.dll
Labels: enhancement, NJOY

#334 minor changes in xs.py
  sandy/core/xs.py
Labels: XS

#341 Get perturbations FY
  sandy/core/endf6.py
  sandy/fy.py
Labels: sampling, FY

#338 Edistr to Endf6
  sandy/__init__.py
  sandy/edistr.py
  sandy/sections/mf5.py
Labels: ENDF6

#342 Read FY samples from excel
  sandy/core/samples.py
Labels: FY

#344 apply perturbations to FY
  sandy/core/endf6.py
Labels: sampling, FY

#345 Apply FY perturbations from cea data
  sandy/core/endf6.py
Labels: sampling, FY

#347 ENDF6 perturb worker test (to v1.1)
  sandy/core/endf6.py
Labels: bug, sampling
